### ISSUE TITLE
build issue "operation not permitted"

### ISSUE THREAD

**Issue by mgsolid** [vito/oci-build-task#11]
#2 [internal] load .dockerignore
#2 ...

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 59B done
#1 DONE 0.1s

#2 [internal] load .dockerignore
#2 transferring context: 2B done
#2 DONE 0.2s
error: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: failed to mount /tmp/buildkit-mount291075877: [{Type:bind Source:/tmp/buildkitd/runc-native/snapshots/snapshots/1 Options:[rbind ro]}]: operation not permitted

**Comment by by-cx** [comment]
We experience very same issue :-(

**Comment by mattdodge** [comment]
Per #5 this typically means you aren't running in privileged mode. Add the `privileged: true` line to your task config
```yml
- task: build image
  privileged: true
  config:
    ...
```

**Comment by vito** [comment]
Per https://github.com/vito/oci-build-task#oci-build-task:

> A stretch goal of this is to support running without privileged: true, though it currently still requires it.

However the README example below was wrong, so I've corrected it.
