### ISSUE TITLE
$TARGET

### ISSUE THREAD

**Issue by mgsolid** [vito/oci-build-task#12]
i have a Dockerfile like:

FROM python AS resource
...

FROM resource AS unit_test
...

FROM resource
...
CMD ["python", " run sth ..."]

when I don't set TARGET in params, it will skip building `unit_test` stage.
when I set TARGET: unit_test in params, will it build to the end?

**Comment by vito** [comment]
is this a question or an issue? `$TARGET` builds the specified target.
