### ISSUE TITLE
Is there support for a privately hosted registry?

### ISSUE THREAD

**Issue by austinlele** [vito/oci-build-task#15]
Hello,

I did not know where else to ask, hopefully this is okay here..

I would love to know if there is support for pushing to a "private" registry? From my understanding the docker-image output resource relies on a repository, but all the examples are from the docker-hub.

Would it be the registry-image-resource that I would be pushing from? If so I can ask this over there.

Thanks!!

**Comment by ebmeierj** [comment]
I think you are right - this question would be more appropriate on the docker-image-resource or registry-image-resource pages.

That being said - what exactly do you mean by "private"? Do you mean privately hosted or requiring authentication... or both? There is definitely support for either of these in the docker-image and registry-image resources. I _did_ run in to an issue where if the FROM resource in your dockerfile requires http basic auth it is not supported - there's an issue open for that. But if you are talking about pushing the resource you just have to configure the image resource to point to the correct registry host with the correct credentials.

**Comment by austinlele** [comment]
I actually did get this all figured out. I am pushing to a hosted registry. I am using the docker-image resource. My issue was providing the "/image name" after the host in the repo field.
