### ISSUE TITLE
Multi-host build cache

### ISSUE THREAD

**Issue by ebmeierj** [vito/oci-build-task#16]
I've turned on the caching for my builds using:
```
                  caches:
                  - path: cache
```

This appears to only cache the build on the worker which it is executed on? We use a pool of workers which is constantly scaling up and down so the workers are not long lived. This severely limits the usefulness of worker based caching.

The above probably makes sense, really. oci-build-task writes the docker image to file and then a subsequent step pushes it to the registry so it makes sense that I might have to set up something similar for the cache as well? However I don't see any resources associated with pushing buildkit cache to my repo. I tried sync'ing the cache directory to s3 and then loading that as an input but that didn't seem to work either.

Is this the intended behavior? Is there a way to cache builds across workers that I'm not seeing?

**Comment by vito** [comment]
This is the intended behavior, at least for now; `buildkit` is capable of other caching mechanisms but this one is by far the simplest. (I see you already figured this out though with #17. :slightly_smiling_face: )
