### ISSUE TITLE
Upstream moby/buildkit dependency

### ISSUE THREAD

**Issue by pn-santos** [vito/oci-build-task#19]
This is more of a query than a request or bug report (I know @vito is busy with v6.0 - leaving this here for consideration). 

This resource image seems to currently depend on `moby/buildkit:master` however the docker hub image `vito/oci-build-task` hasn't been updated in 2 months.

So my question is twofold:

- If this is supposed to track `moby/buildkit:master` should it not auto-trigger (or trigger on a regular basis) on new versions of `moby/buildkit:master`?
- Would it be preferable to track a particular tag of `moby/buildkit`? as in `moby/buildkit:v0.6.3` for example? (and bump that explicitly as needed)

PS: Not sure if the pipeline building this resource image has a particular pinned SHA of `moby/buildkit:master`

**Comment by vito** [comment]
> * Would it be preferable to track a particular tag of `moby/buildkit`? as in `moby/buildkit:v0.6.3` for example? (and bump that explicitly as needed)

This would be preferable. I had to point to `master` at one point because I needed some changes that hadn't shipped. I'm going to point it back to v0.6.4.
