### ISSUE TITLE
Recent jboss/keycloak images trigger `wrong diff id calculated on extraction`

### ISSUE THREAD

**Issue by camelpunch** [vito/oci-build-task#20]
I have a [repro repo with a README](https://github.com/camelpunch/oci-build-task-repro).

You'll want to edit and run the `run` script.

I tried a few tags, where BAD means it triggers the error (chronological order from [dockerhub](https://hub.docker.com/r/jboss/keycloak/tags)):
- 8.0.1: BAD
- 8.0.0: BAD
- 7.0.1: BAD
- 5.0.0: GOOD
- 7.0.0: GOOD
- 6.0.1: GOOD

Did I misconfigure? Did jboss screw up their images? Is there a bug? Are we all doomed?

The BAD tags work fine with `docker-image-resource`.

**Comment by vito** [comment]
fixed in v0.2.0 - thanks for the repro!

**Comment by camelpunch** [comment]
No, thank you!
