### ISSUE TITLE
Tag for recent 0.7.0 bump?

### ISSUE THREAD

**Issue by pn-santos** [vito/oci-build-task#25]
Hi, seems a tag wasn't created after the buildkit version bump to `0.7.0`

I ran into an issue when using `0.2` that didn't happen and before, tried the `master` tag and worked fine :+1: (I assume `master` has `0.7.0` of buildkit?)

@vito would it possible to tag and push a version of the resource with buildkit `0.7.0` or is there some know issue preventing this? (I can for now depend on `master` tag but would be better to depend on an immutable tag if possible)

In case anyone can decipher this the error is:
```
#4 ERROR: failed to extract layer sha256:8648bd3934e1b3cf6a6cc225776bfdf7381d1bff8c1ce9d20e9fe65b300d14d5: mount callback failed on /tmp/containerd-mount818919733: mkdir /tmp/containerd-mount818919733/var/run: invalid argument
```
the exact same build works ok with the tag `0.1` and `master` of `vito/oci-build-task` but throws that error with `0.2`

**Comment by vito** [comment]
done! v0.3.0 will be published shortly
