### ISSUE TITLE
min cache settings results in poor caching 

### ISSUE THREAD

**Issue by databus23** [vito/oci-build-task#26]
Hi,

I'm wondering if the cache export with `mode=min` was made deliberately here:
https://github.com/vito/oci-build-task/blob/master/task.go#L60

In my observation this leads to almost no cache effect in my multi-stage builds of go binaries as only layers of the final image are actually cached. In general in multistage build the final image does not consist of many layers (e.g. in the case of go: mostly copy the build binary into a very small base image).
Changing the setting to `max` and rebuilding the image does lead to much better cache results (e.g. the expensive steps in the intermediate builder image being cached).

Can we change the setting to `max` or should we maybe make it configurable?

**Comment by drahnr** [comment]
I would be much in favour of making it configurable, after all this change has potential to significantly impact on disk requirements IIUC

**Comment by databus23** [comment]
@drahnr Yes it would. In my test the cache directory went from 50MB to 500MB.
I'm fine with making it configurable but one could argue that the setting is already configurable (its off by default and has to be disabled). The cache will always proportionally sized to the number and size of layers that are being cached. If you have a single stage build with many big layers you will get a big cache already. its just for multi-stage builds that currently you get a small cache but that also means the cache does not yield much benefits. I think in most multi-stage builds the current setting gives you close to no benefit.

**Comment by vito** [comment]
It seems like there's consensus to switch to `max`, and the reasoning makes sense to me, so I'm down to change the default. I don't remember a particular reason for setting `mode=min` - if I had to guess, I probably just saw that it was the default and wanted to be explicit in case the default changed in the future.

**Comment by ConnorJC3** [comment]
Just ran into this myself, I use a multi-stage build and was wondering why my 30+ minute early stage was receiving no caching. +1 to changing it to max or making it configurable.
