### ISSUE TITLE
docs for contributing

### ISSUE THREAD

**Issue by jmccann** [vito/oci-build-task#39]
I'd be nice to have documentation around how to contribute to this project.

I'm trying to work on #37 and had a hard time figuring out how to run tests.

This is what I ended up having to do ... not sure if there's a better or more correct way.

```
docker run --privileged -it -v $(pwd):/code ubuntu /bin/sh
apt update
apt install curl golang
cd /code
scripts/test # repeat this as needed
```

Also had to spend a little time to figure out how to build with experimental stuff using `DOCKER_BUILDKIT=1`:

```
DOCKER_BUILDKIT=1 docker build -t vito/oci-build-task:rc .
```

**Comment by tomjw64** [comment]
I've found something like `docker run -it --privileged --mount type=bind,source=$(pwd),target=/code golang /bin/bash` works great, rather than having to start with ubuntu and mess with apt.

**Comment by vito** [comment]
Finally got around to this - not perfect yet but it's a start!

**Comment by jmccann** [comment]
I think it's good enough to close this issue.  Thanks for getting that out there!
