### ISSUE TITLE
To build an image which base is in ECR and needs additional authentication

### ISSUE THREAD

**Issue by clamorisse** [vito/oci-build-task#57]
Is there a way to build an image based on another image stored in our ECR in AWS? We haven't been able to pass the proper authentication to pull the base image, failing with an ACCESS DENIED error.
Thanks.

**Comment by chenbh** [comment]
The recommended way is to fetch the image via `registry-image-resource` first and then pass it into the build-task. See https://github.com/vito/oci-build-task/issues/14#issuecomment-757014837 for more details

**Comment by ringods** [comment]
I just bumped into this because I had a similar situation, only my base image was on Google Cloud Artifact Registry. I implemented the setup as described by @vito in #52 and it worked flawlessly.

**Comment by vito** [comment]
Going to close this per the last two comments - that's the recommended approach, as supporting the same level of auth/access that the `registry-image` resource type supports is a lot of duplicate effort. Using `registry-image` resource to represent the base image also allows the input to be versioned and controlled more precisely.
