### ISSUE TITLE
Move to an organisation repository

### ISSUE THREAD

**Issue by pidster** [vito/oci-build-task#6]
If this is the recommended task (it appears to be, per https://github.com/concourse/builder-task), can I suggest that it be moved to the Concourse organisation to reflect its status?

**Comment by vito** [comment]
I'm not sure if I want to do this, or at least not yet. :thinking: I think this would make sense if and when the full Concourse team is ready to support and maintain it, but right now it's just me, and I would rather its ownership reflect that as I expect that will be the pattern for most third-party resources/tasks/etc.

In my experience with our own 'core' resources, having it in the concourse org kind of does the opposite of what users want: it *appears* that many people are maintaining it, but really no one ends up feeling responsible for it and the community doesn't really have a clear person to ping.

Happy to hear the other side of this though.

**Comment by vito** [comment]
Another bit of context: I don't think 'recommended' tasks and resources should always live in the 'concourse' organization. If you look at how programming language ecosystems are built, they don't put every package in the `golang` org or in the stdlib for example.

It does help with discoverability, but we're currently working on a better solution for that anyway, something kind of like [Elm's package repository](https://package.elm-lang.org/).
